### ISSUE TITLE
using local blobstore for hostname results in multiple errors

### ISSUE THREAD

**Issue by rirze** [HewlettPackard/python-ilorest-library#64]
Hi,

I'm trying to use this library for monitoring the health of some servers I'm using. I began adapting the simple redfish-quickstart file that's available under the examples directory. As per instructions, I also have hprest_chif.so available on my system. The relevant part of the script is below:
 
``` python
import redfish

# When running on the server locally use the following commented values
iLO_host = "blobstore://."
iLO_account = "None"
iLO_password = "None"


redfish_obj = redfish.redfish_client(base_url=iLO_host,
                                     username=iLO_host,
                                     password=iLO_password)

redfish_obj.login(auth="session")

```

When I try to run this with python3.6, I get the following errors: 
```
Traceback (most recent call last): 
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 955, in __init__
    password=password) 
  File "/usr/lib/python3.6/site-packages/redfish/hpilo/risblobstore2.py", line 858, in initializecreds
    dll = BlobStore2.gethprestchifhandle()
  File "/usr/lib/python3.6/site-packages/redfish/hpilo/risblobstore2.py", line 837, in gethprestchifhandle
    raise ChifDllMissingError(excp)
redfish.hpilo.risblobstore2.ChifDllMissingError: '_Environ' object has no attribute 'has_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_memory_status.py", line 16, in <module>
    password=iLO_password)
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 1226, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 966, in __init__
    if excp.message == 'chif': 
AttributeError: 'ChifDllMissingError' object has no attribute 'message'
```

When I try running with python 2.7:
```
Traceback (most recent call last): 
  File "check_memory_status.py", line 16, in <module>
    password=iLO_password) 
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1226, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 955, in __init__
    password=password)
  File "/usr/lib/python2.7/site-packages/redfish/hpilo/risblobstore2.py", line 858, in initializecreds
    dll = BlobStore2.gethprestchifhandle()
  File "/usr/lib/python2.7/site-packages/redfish/hpilo/risblobstore2.py", line 835, in gethprestchifhandle
    BlobStore2.setglobalhprestchifrandnumber(libhandle)
  File "/usr/lib/python2.7/site-packages/redfish/hpilo/risblobstore2.py", line 846, in setglobalhprestchifrandnumber
    libbhndl.updaterandval.argtypes = [c_ushort]
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 378, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self)) 
AttributeError: /lib64/hprest_chif.so: undefined symbol: updaterandval
```

Remote connections (using an explicit IP address) to connect to the iLO works fine but I want to avoid using hardcoded IPs and account credentials in my script. Any help to fix these issues would be greatly appreciated.

**Comment by jimmylin212** [comment]
Hi @rirze 

We have the update for `ilorest_chif` binary, and we will update the download link as soon as possible.

**Comment by jimmylin212** [comment]
Hi @rirze ,

Please download the latest version of `ilorest_chif` from README again. The new version works as expect.

Thank you.

**Comment by injan0913** [comment]
@rirze We've fixed the python3 issue and it will be in next release

**Comment by rirze** [comment]
When is the next release? I'm currently getting this issue with python 3.6:
```
Traceback (most recent call last): 
  File "check_memory_status.py", line 35, in <module>
    raise e
  File "check_memory_status.py", line 19, in <module>
    redfish_obj.login(auth="session") 
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 894, in login
    raise InvalidCredentialsError(delay)
redfish.rest.v1.InvalidCredentialsError: 0
```

Reporting this error in case this was not addressed in your issue fix.

**Comment by jimmylin212** [comment]
@rirze 

- When you using inband communication, please change the auth to `basic`.
- Yes, we already fix the issue you mention in the next version. 

Thank you.

**Comment by rirze** [comment]
Seems like I still can't python3 to work: 

```
Traceback (most recent call last): 
  File "check_memory_status.py", line 36, in <module>
    raise e 
  File "check_memory_status.py", line 22, in <module>
    response = redfish_obj.get("/redfish/v1/systems/1/Memory", None)
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 634, in get
    headers=headers)
  File "/usr/lib/python3.6/site-packages/redfish/rest/v1.py", line 1035, in _rest_request
    reqpath = path.replace('//', '/')
TypeError: a bytes-like object is required, not 'str'
```

Looks like the package is not accounting for python3 bytes vs strings conversion properly.

**Comment by rirze** [comment]
Any update on this? Are there plans to fix this?

**Comment by Yergidy** [comment]
@rirze Yes. We are working on a fix now. I will update the issue once it has been addressed. In the meantime, if you need it to work now, can you try running it with the latest Python 2?

**Comment by Yergidy** [comment]
@rirze A fix for the local python 3 issues have been committed. Please pull the master and see if that fixes your issue.
